[package]
name = "sqlite-glance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.11"
rusqlite = "0.29.0"
yansi = { version = "1.0.0-rc", features = ["detect-tty", "detect-env"] }
