name: tests

on: [push, pull_request]

jobs:
  test:
    name: cargo check & test
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo check
          cargo test
